#! /usr/bin/env sh

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
    set -x
fi

# The sed expression here replaces all backslashes by forward slashes.
# This helps our Windows users, while not bothering our Unix users.
export GITWORKFLOW_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

usage() {
    echo "usage git workflow <subcommand>"
    echo
    echo "Available subcommands are:"
    echo "  start       Create a new issue branch"
    echo "  commit      Create a commit in the current issue branch. Adds the markeers to connect with the issue tracker."
    echo "Try 'git workflow <subcommand> -h for details"
}

main() {
    if [ $# -lt 1 ]; then
        usage
        exit 1
    fi

    SUBCOMMAND="$1"; shift

    if [ ! -e "$GITWORKFLOW_DIR/workflow/$SUBCOMMAND.py" ]; then
        usage
        exit 1
    fi

    python "$GITWORKFLOW_DIR/workflow/$SUBCOMMAND.py" $@
}

main "$@"
